LocadoraDeVeiculos/Controllers/VeiculoController.cs
using LocadoraDeVeiculos.Dados;
using LocadoraDeVeiculos.Dominio;
using LocadoraDeVeiculos.Metodos;
using Microsoft.Ajax.Utilities;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LocadoraDeVeiculos.Controllers
{
    public class VeiculoController : Controller
    {
        Conexao banco = new Conexao();
        // GET: Veiculo
        public ActionResult Cadastro()
        {
            List<SelectListItem> categoria = new List<SelectListItem>();

            var cmd = string.Format("select * from Categoria");
            var rdr = banco.ExecultarConsulta(cmd);

            while (rdr.Read())
            {
                categoria.Add(new SelectListItem
                {
                    Value = rdr[0].ToString(),
                    Text = rdr[1].ToString()

                });
            }

            ViewBag.categorias = new SelectList(categoria, "Value", "Text");
            rdr.Close();

            List<SelectListItem> marca = new List<SelectListItem>();

            cmd = string.Format("select * from marca");
            rdr = banco.ExecultarConsulta(cmd);

            while (rdr.Read())
            {
                marca.Add(new SelectListItem
                {
                    Value = rdr[0].ToString(),
                    Text = rdr[1].ToString()

                });
            }
            ViewBag.marcas = new SelectList(marca, "Value", "Text");
            rdr.Close();
            return View();
        }
        [HttpPost]
        public ActionResult Cadastro(HttpPostedFileBase file, Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/Imagens"), _FileName);
                    file.SaveAs(_path);
                    var imagepath = "~/Imagens/" + _FileName;
                    veiculo.imagem = imagepath;
                    var metodo = new MetodosGerais();
                    metodo.CadastroVeiculo(veiculo);
                }
                return RedirectToAction("Lista");
            }
            return View(veiculo);
        }
        
        public ActionResult Lista()
        {
            var metodo = new MetodosGerais();
            var veiculo = metodo.ListarVeiculo();
            return View(veiculo);
        }
        public ActionResult Editar()
        {
            List<SelectListItem> categoria = new List<SelectListItem>();

            var cmd = string.Format("select * from Categoria");
            var rdr = banco.ExecultarConsulta(cmd);

            while (rdr.Read())
            {
                categoria.Add(new SelectListItem
                {
                    Value = rdr[0].ToString(),
                    Text = rdr[1].ToString()

                });
            }

            ViewBag.categorias = new SelectList(categoria, "Value", "Text");
            rdr.Close();

            List<SelectListItem> marca = new List<SelectListItem>();

            cmd = string.Format("select * from marca");
            rdr = banco.ExecultarConsulta(cmd);

            while (rdr.Read())
            {
                marca.Add(new SelectListItem
                {
                    Value = rdr[0].ToString(),
                    Text = rdr[1].ToString()

                });
            }
            ViewBag.marcas = new SelectList(marca, "Value", "Text");
            rdr.Close();
            return View();
        }
    }
}

LocadoraDeVeiculos/Views/Veiculo/Cadastro.cshtml
@model LocadoraDeVeiculos.Dominio.Veiculo

@{
    ViewBag.Title = "Cadastro de veiculos";
    Layout = "~/Views/Shared/_ViewAdministrativa.cshtml";
}
    <body>

        <h2>Cadastro</h2>


        @using (Html.BeginForm("Cadastro", "Veiculo", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()


            
            <hr />
            <div class="form" style="margin:5%">
                <h4>Veiculo</h4>

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <table width="100%">
                    <tr>
                        <td>
                            <div class="form-group">
                                @Html.LabelFor(model => model.idCategoria, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.idCategoria, ViewBag.categorias as SelectList, "--Escolha a categoria--", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.idCategoria, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                @Html.LabelFor(model => model.idMarca, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.idMarca, ViewBag.marcas as SelectList, "--Escolha a marca--", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.idMarca, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                @Html.LabelFor(model => model.modelo, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.modelo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.modelo, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="form-group">
                                @Html.LabelFor(model => model.placa, htmlAttributes: new { @class = "control-label col-md-10" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.placa, new { htmlAttributes = new { @class = "form-control", id = string.Format("placa") } })
                                    @Html.ValidationMessageFor(model => model.placa, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                @Html.LabelFor(model => model.chassi, htmlAttributes: new { @class = "control-label col-md-10" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.chassi, new { htmlAttributes = new { @class = "form-control", id = string.Format("chassi") } })
                                    @Html.ValidationMessageFor(model => model.chassi, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-10" })
                                <div class="col-md-10">
                                    <select id="status" name="status" class="form-control">
                                        <option selected value="Disponivel">Disponivel</option>
                                        <option value="Indisponivel">Indisponivel</option>
                                    </select>
                                    @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="form-group">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-camera-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M10.5 8.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                                    <path fill-rule="evenodd" d="M2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2zm.5 2a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm9 2.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0z" />
                                </svg>
                                @Html.LabelFor(model => model.imagem, htmlAttributes: new { @class = "control-label col-md-10" })
                                <div class="col-md-10">
                                    <input type="file" name="file" id="file" />
                                    @Html.ValidationMessageFor(model => model.imagem, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <div>
                    <div style="float:right">
                        <input type="submit" value="Cadastrar" class="btn take-fundo" />
                    </div>
                </div>
                <a class="btn take-fundo btn-lg" href="~/Veiculo/Lista" style="float:left">
                    <svg class="bi bi-arrow-left-circle-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-7.646 2.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L6.207 7.5H11a.5.5 0 0 1 0 1H6.207l2.147 2.146z" />
                    </svg>
                </a>

            </div>
        }


        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
            <script>
                $(document).ready(function () {
                    $("#placa").inputmask("mask", { "mask": "aaa-9999" });
                    $("#cpf").inputmask("mask", { "mask": "999.999.999-99" }, { reverse: true });
                    $("#cep").inputmask("mask", { "mask": "99999-999" });
                    $("#chassi").inputmask("mask", { "mask": "#################" });
                    $("#preco").inputmask("mask", { "mask": "999.999,99" }, { reverse: true });
                    $("#valor").inputmask("mask", { "mask": "#.##9,99" }, { reverse: true });
                    $("#ip").inputmask("mask", { "mask": "999.999.999.999" });
                });
            </script>
        }
    </body>

LocadoraDeVeiculos/Views/Veiculo/Lista.cshtml
@model IEnumerable<LocadoraDeVeiculos.Dominio.Veiculo>

@{
    ViewBag.Title = "Veiculos";
    Layout = "~/Views/Shared/_ViewAdministrativa.cshtml";
}

<h2>Lista de veículos</h2>
<a class="btn take-fundo btn-lg" href="~/Funcionario/Index" style="float:left">
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-left-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
        <path fill-rule="evenodd" d="M8.354 11.354a.5.5 0 0 0 0-.708L5.707 8l2.647-2.646a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708 0z" />
        <path fill-rule="evenodd" d="M11.5 8a.5.5 0 0 0-.5-.5H6a.5.5 0 0 0 0 1h5a.5.5 0 0 0 .5-.5z" />
    </svg>
</a>
<a class="btn btn-take btn-lg" style="float:right;" href="~/Veiculo/Cadastro">
    <svg class="bi bi-plus-circle-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4a.5.5 0 0 0-1 0v3.5H4a.5.5 0 0 0 0 1h3.5V12a.5.5 0 0 0 1 0V8.5H12a.5.5 0 0 0 0-1H8.5V4z" />
    </svg>
    <br />
</a>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.categoria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.marca)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.modelo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.placa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.chassi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
       
        <td>
            @Html.DisplayFor(modelItem => item.categoria)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.marca)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.modelo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.placa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.chassi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        
        <td>
            @Html.ActionLink("Ver Detalhes/Editar", "Editar", new { id=item.id })
        </td>
    </tr>
}

</table>